### PR TITLE
task2

### PR DESCRIPTION
**Pull request by dmytro-kryvyi**

### CODE REVIEW

**Comment by andrii-s-spitzer-lpnu-ua** [comment]
did we already have meeting about tas1 and did you recive mark?

**Comment by dmytro-kryvyi** [comment]
No, we still haven't had a meeting about the task1 and I haven't
received a mark. The PR of the task1 was approved, so I did the second

**Comment by andrii-s-spitzer-lpnu-ua** [comment]
Then please chat me in telegram and we will submit meeting

**Comment by dmytro-kryvyi** [comment]
You asked to be reminded to confirm my request. I got my first lab grade yesterday.

**Review by andrii-s-spitzer-lpnu-ua — APPROVED** [review]

**Pull request merged**
